### ISSUE TITLE
mujoco_py issue when creating a conda environment. Same code runs fine in a Python venv environment. 

### ISSUE THREAD

**Issue by ChristosPeridis** [vikashplus/robohive#102]
Hello dear Dr. Vikash,

How are you doing? I hope you are doing well. I had to conduct some research during the past week so I postponed working on the RoboHive API. I am starting again from today. Before I had successfully made a Python3 venv virtual environment, where I installed RoboHive.

 In my system I had downloaded and extracted under the ".mujoco" folder mujoco200 simulator, along with its key and license. In order to make visible to the virtual environment the mujoco200 simulator I appended the following to the activate file of the bin folder of my venv virtual environment:
 
 
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/.mujoco/mujoco200/bin
export MUJOCO_PY_MJKEY_PATH=~/.mujoco/mjkey.txt
export MUJOCO_PY_MUJOCO_PATH=~/.mujoco/mujoco200

After appending the above in the activate file of my venv environment I activated it and install RoboHive API from the cloned GitHub repository with the following command:

 pip install -e ".[mujoco]"

Then I ran the example command :  python robohive/utils/examine_env.py -e FrankaReachRandom-v0

And everything ran fine, I was able to see the simulation .

However, when I attempted to follow the same steps to install RoboHive API in a conda environment it did not work  as expected. The installation seemed to proceed well, unfortunately though, when executing the example code I received the following error:

Compiling /home/lunet/cocp5/anaconda3/envs/robohiveRL04/lib/python3.8/site-packages/mujoco_py/cymj.pyx because it changed.
[1/1] Cythonizing /home/lunet/cocp5/anaconda3/envs/robohiveRL04/lib/python3.8/site-packages/mujoco_py/cymj.pyx
Traceback (most recent call last):
  File "/home/lunet/cocp5/anaconda3/envs/robohiveRL04/lib/python3.8/site-packages/robohive/utils/import_utils.py", line 3, in mujoco_py_isavailable
    import mujoco_py
  File "/home/lunet/cocp5/anaconda3/envs/robohiveRL04/lib/python3.8/site-packages/mujoco_py/__init__.py", line 15, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/home/lunet/cocp5/anaconda3/envs/robohiveRL04/lib/python3.8/site-packages/mujoco_py/builder.py", line 499, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/home/lunet/cocp5/anaconda3/envs/robohiveRL04/lib/python3.8/site-packages/mujoco_py/builder.py", line 106, in load_cython_ext
    mod = load_dynamic_ext('cymj', cext_so_path)
  File "/home/lunet/cocp5/anaconda3/envs/robohiveRL04/lib/python3.8/site-packages/mujoco_py/builder.py", line 125, in load_dynamic_ext
    return loader.load_module()
ImportError: /home/lunet/cocp5/anaconda3/envs/robohiveRL04/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/x86_64-linux-gnu/libLLVM-15.so.1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "robohive/utils/examine_env.py", line 110, in <module>
    main()
  File "/home/lunet/cocp5/anaconda3/envs/robohiveRL04/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/lunet/cocp5/anaconda3/envs/robohiveRL04/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/lunet/cocp5/anaconda3/envs/robohiveRL04/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lunet/cocp5/anaconda3/envs/robohiveRL04/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "robohive/utils/examine_env.py", line 55, in main
    env = gym.make(env_name) if env_args==None else gym.make(env_name, **(eval(env_args)))
  File "/home/lunet/cocp5/anaconda3/envs/robohiveRL04/lib/python3.8/site-packages/gym/envs/registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "/home/lunet/cocp5/anaconda3/envs/robohiveRL04/lib/python3.8/site-packages/gym/envs/registration.py", line 101, in make
    env = spec.make(**kwargs)
  File "/home/lunet/cocp5/anaconda3/envs/robohiveRL04/lib/python3.8/site-packages/gym/envs/registration.py", line 73, in make
    env = cls(**_kwargs)
  File "/home/lunet/cocp5/anaconda3/envs/robohiveRL04/lib/python3.8/site-packages/robohive/envs/arms/reach_base_v0.py", line 41, in __init__
    super().__init__(model_path=model_path, obsd_model_path=obsd_model_path, seed=seed)
  File "/home/lunet/cocp5/anaconda3/envs/robohiveRL04/lib/python3.8/site-packages/robohive/envs/env_base.py", line 57, in __init__
    self.sim = SimScene.get_sim(model_path)
  File "/home/lunet/cocp5/anaconda3/envs/robohiveRL04/lib/python3.8/site-packages/robohive/physics/sim_scene.py", line 56, in get_sim
    return SimScene.create(model_handle=model_handle, backend=SimBackend.MUJOCO_PY)
  File "/home/lunet/cocp5/anaconda3/envs/robohiveRL04/lib/python3.8/site-packages/robohive/physics/sim_scene.py", line 42, in create
    from robohive.physics import mjpy_sim_scene  # type: ignore
  File "/home/lunet/cocp5/anaconda3/envs/robohiveRL04/lib/python3.8/site-packages/robohive/physics/mjpy_sim_scene.py", line 15, in <module>
    import_utils.mujoco_py_isavailable()
  File "/home/lunet/cocp5/anaconda3/envs/robohiveRL04/lib/python3.8/site-packages/robohive/utils/import_utils.py", line 11, in mujoco_py_isavailable
    raise ModuleNotFoundError(f"{e}. {help}")
ModuleNotFoundError: /home/lunet/cocp5/anaconda3/envs/robohiveRL04/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/x86_64-linux-gnu/libLLVM-15.so.1). 
        Options:
            (1) follow setup instructions here: https://github.com/openai/mujoco-py/
            (2) install mujoco_py via pip (pip install mujoco_py)
            (3) install free_mujoco_py via pip (pip install free-mujoco-py)

I tried to create the conda environment and install RoboHive with all proposed pip install comands, both the ones for PyPi and the ones from the GitHub repository. Despite my efforts however, the same issue was always present.

As a final attempt I created an activate.sh file inside the bin folder of the conda environment that I was working on, and I appended at the end the same export commands to the ones I appended to the activate file of the venv environment. I also created an deactivate.sh in order to unset these environment variables when deactivating the environment. It did not work either ...

What is the real cause of this error and how can I overcome this?

It is  important to note that the same issue was present both in my WSL2 Ubuntu 20.04.06 LTS system and in a native Linux Ubuntu 22.04 LTS workstation system.

I also wanted to inform you that I am working on the creation of the document that describes the setup procedure of my WSL2 setup where I am working with the RoboHive API, and I am planning to send it you as soon as possible!

Thank you very much in advance for your valuable help!!!

Kind regards,

Christos Peridis

**Comment by vikashplus** [comment]
Hi Christos, 
Thanks for your interest and efforts on RoboHive. 

From the error messages, it seems like mujoco_py installation issues. Can you try something like this to check if you have a healthy mujoco_py installation?
```
conda activate <env-name>
python -c "import mujoco_py"
```
Your first step will be to get above to succeed before attempting anything with RoboHive. Here are a few helpful resources to help you with mujoco_py 
- [torchRL guide for Old bindings (≤ 2.1.1): mujoco-py](https://pytorch.org/rl/reference/generated/knowledge_base/MUJOCO_INSTALLATION.html)
- [mjRL installation guide](https://github.com/aravindr93/mjrl/tree/master/setup#installation)

From the errors, it seems like an library issue. Pay attention to the following suggestions 
`sudo apt-get install libgl1-mesa-dev libgl1-mesa-glx libglew-dev libosmesa6-dev build-essential libglfw3`

Alternatively, you can use RoboHive with MuJoCo's official bindings. Please refer to the [RoboHive's installation FAQs](https://github.com/vikashplus/robohive/wiki/6.-Tutorials-&-FAQs#installation) for details on how to pick you simulation backend.

**Comment by ChristosPeridis** [comment]
Hello dear Dr. Vikash,

Thank you so much for your immediate response. Also thank you very much for your support material. I have tried the first approach and it did not work in the native Ubuntu machine at work. I am still working on it and I will also try the technique in my personal machine with the WSL2 set up. I will report back to you as soon as I have any updates!

Thank you very much for your valuable help!!!

Kind regards,

Christos Peridis
